// <auto-generated />
namespace Vidly.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Add_ReleaseDate_AddedDate_NumberStock_GenreId_Column_in_Movies : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_ReleaseDate_AddedDate_NumberStock_GenreId_Column_in_Movies));
        
        string IMigrationMetadata.Id
        {
            get { return "202403190254331_Add_ReleaseDate_AddedDate_NumberStock_GenreId_Column_in_Movies"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
